apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application02
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    repoURL: https://github.com/tuvx2000/CD-argocd-app-config
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    # server: https://kubernetes.default.svc 
    namespace: myapp02
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true