apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: python:3.9
          ports:
            - containerPort: 5000
          command: ["python", "-u"]
          args: ["-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]